export const types = {
    POKEMON_LIST_LOADING: 'POKEMON_LIST_LOADING',
    POKEMON_LIST_SUCCESS: 'POKEMON_LIST_SUCCESS',
    POKEMON_LIST_FAIL: 'POKEMON_LIST_FAIL',
    
    POKEMON_MULTIPLE_LOADING: 'POKEMON_LIST_LOADING',
    POKEMON_MULTIPLE_SUCCESS: 'POKEMON_LIST_SUCCESS',
    POKEMON_MULTIPLE_FAIL: 'POKEMON_LIST_FAIL',

    
}